### ISSUE TITLE
Hide the `[@zenuml/core] Store is a function and is not initiated in 1 second.` warning

### ISSUE THREAD

**Issue by aloisklink** [mermaid-js/zenuml-core#169]
The [`@mermaid-js/mermaid-cli` program](https://github.com/mermaid-js/mermaid-cli) uses `@mermaid-js/mermaid-zenuml` as a dependency, which then uses `@zenuml/core`.

It sounds like a `[@zenuml/core] Store is a function and is not initiated in 1 second.` warning is being logged due to the following line of code:

https://github.com/mermaid-js/zenuml-core/blob/7658a1c4c84aa894d6e90580754b1bfe818cadeb/src/store/Store.ts#L14-L21

This warning is causing some confusion with `@mermaid-js/mermaid-cli` users (see https://github.com/mermaid-js/mermaid-cli/issues/588), and it makes our test logs messier.

It looks like a timer is started whenever `@zenuml/core` is imported, and that warning is automatically printed if ZenUML isn't used within 1 second.

Is there any chance we can remove this warning, or at least hide it by default?

**Comment by l1n** [comment]
Bumping this, would love to have this option

**Comment by db4rr** [comment]
I also support this

**Comment by m1rm** [comment]
maybe this https://github.com/mermaid-js/zenuml-core/pull/193 helps to reduce the confusion. My intention was to make the warning sound like a warning and not like an error

**Comment by MrCoder** [comment]
This warning, originally put in place due to issues with clients having to initialise the store manually, is no longer relevant. These issues were prevalent in the early days, but our new API has largely eliminated the prospect of the store not initializing. have removed the warning via this pull request: https://github.com/mermaid-js/zenuml-core/pull/194.

**Comment by MrCoder** [comment]
Fixed in https://www.npmjs.com/package/@zenuml/core/v/3.24.13

**Comment by dontry** [comment]
Hi @aloisklink, do you want me to bump  @zeuml/core version to the latest in the `@mermaid-js/mermaid-zenuml` dependencies?

**Comment by aloisklink** [comment]
> Hi @aloisklink, do you want me to bump @zeuml/core version to the latest in the @mermaid-js/mermaid-zenuml dependencies?

It should be fine, since the current `^3.23.27` supports `3.24.13`.

https://github.com/mermaid-js/mermaid/blob/d16e46a3860bce8c4ae1d12308c5d9cf8055bcf7/packages/mermaid-zenuml/package.json#L36

I think one of the automated @renovatebot PRs like https://github.com/mermaid-js/mermaid/pull/5961 will bump the `pnpm-lock.yaml` file and therefore the version used for tests, but since it won't update the `package.json` file, there won't be a need for an update.

**Comment by ENate** [comment]
Hi. I installed mermaid/mermaid-cli on Ubuntu and got this error while using the markdown plugin in Neovim. It seems the error is still not fixed. Is there any way to handle the issue? Thanks.

**Comment by MrCoder** [comment]
Hi @aloisklink, no new versions have been published to npmjs.com for [@mermaid-js/mermaid-zenuml](https://www.npmjs.com/package/@mermaid-js/mermaid-zenuml?activeTab=versions) since 3rd May 2024. @zenuml/core v3.24.13 was released Oct 2024.
